# 데이터 분석 라이브러리

- numpy : 연속형, 수치형 자료 과학/수학/통계 연산을 수행하는 라이브러리 for 딥러닝/비정형 data 다루는 데 쓰임
- pandas : 정형데이터(excle, csv, sQL)등 을 다룸
- matplot : for 시각화
- seaborn : 정형데이터 통계 분석 시각화 lib
- plotlly : 정형데이터 동적(반응형) 시각화 lib
- missingno : 별측치 패턴, 수, 시각화 lib
- scipy : science + python 응용통계 (가설검정/ 회귀분석 / 시계열) lib
- scikit : science + python + toolkit + learning 정형데이터를 이용한 머신러닝 lib
- tenserflow : 딥러닝용 비정형 데이터 lib
- keras : tenserflow기반 딥러닝 lib
- pytorch : 비정형 데이터 관련 lib
- konlpy : 한국어 자연어 처리 lib

# numpy
- numeric + python
- 정형데이터의 기본이 되는 초기 data 분석에 쓰임 지금은 비정형데이터 분석에 쓰임

In [3]:
import numpy as np

In [5]:
list= [1,1,2]
list.mean()
#error

AttributeError: 'list' object has no attribute 'mean'

In [23]:
data1= np.array([1,2,3])
type(data1)

#ndarray 몇 차원인지 n-dimensional

numpy.ndarray

In [25]:
data1.ndim

1

In [31]:
np.array([1]).ndim

1

In [33]:
np.array([1,2]).ndim

1

In [39]:
# 0 : scala
# 1 : vector
# 2 : matrix

In [9]:
data1.mean()

2.0

In [11]:
data1.var()

0.6666666666666666

In [13]:
[x for x in range(0, 11)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(1, 20 ,3) #1부터 20까지 3의 간격으로 출력

array([ 1,  4,  7, 10, 13, 16, 19])

In [41]:
np.linspace(1,10,7)# 1부터 10 까지 7개로 쪼갬

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

# 행렬

In [44]:
m1 = [ [0,0,1] , [0,1,0] , [1,0,0]]
m1

[[0, 0, 1], [0, 1, 0], [1, 0, 0]]

In [46]:
data1 = np.array(m1)
data1

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]])

In [48]:
type(data1)

numpy.ndarray

In [52]:
data1.ndim  # 2 = matrix

2

In [56]:
# 행렬의 연산

data4 = np.array( [[1,2] , [3,4] , [4,5], [5,6]])
data5 = np.array( [[1,2] , [3,4] , [4,5], [5,6]])

data4 + data5

array([[ 2,  4],
       [ 6,  8],
       [ 8, 10],
       [10, 12]])

In [60]:
# 행렬의 곱

#앞 행과 뒷 행이 같아야 계산가능

data6 = np.array( [[1,2] , [3,4] , [5,6]])
data7 = np.array( [[1,2,3] , [4,5,6]])

print(data6)
print(data7)
data6@data7


[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [68]:
# 매트릭스 인덱싱
data9 = np.array( [['a','b','c'], ['d','e','f'] ,['g','h','f']])
data9

array([['a', 'b', 'c'],
       ['d', 'e', 'f'],
       ['g', 'h', 'f']], dtype='<U1')

In [72]:
data9[0]

array(['a', 'b', 'c'], dtype='<U1')

In [74]:
data9[:1]

array([['a', 'b', 'c']], dtype='<U1')

In [78]:
data9[0,2] = 'z'
data9

array([['a', 'b', 'z'],
       ['d', 'e', 'f'],
       ['g', 'h', 'f']], dtype='<U2')

In [76]:
data9 = np.array(data9, dtype = '<U2')
data9

array([['a', 'b', 'c'],
       ['d', 'e', 'f'],
       ['g', 'h', 'f']], dtype='<U2')

In [80]:
data9[0,2] = 'a1'
data9

array([['a', 'b', 'a1'],
       ['d', 'e', 'f'],
       ['g', 'h', 'f']], dtype='<U2')

In [86]:
#veritcla stack 세로줄 하나 추가
np.vstack([data9, [1,2,3]])

array([['a', 'b', 'a1'],
       ['d', 'e', 'f'],
       ['g', 'h', 'f'],
       ['1', '2', '3']], dtype='<U11')

In [100]:
np.hstack([data9, [[5],[6],[7]]])

array([['a', 'b', 'a1', '5'],
       ['d', 'e', 'f', '6'],
       ['g', 'h', 'f', '7']], dtype='<U11')

# 재구조화

In [103]:
data8 = np.array([1,25,46,89])
data8

array([ 1, 25, 46, 89])

In [105]:
data8.reshape(2,2) #재구조화

array([[ 1, 25],
       [46, 89]])

In [116]:
data9 = np.linspace(1,25,9)
data9

array([ 1.,  4.,  7., 10., 13., 16., 19., 22., 25.])

In [122]:
data9.reshape(3,3)

array([[ 1.,  4.,  7.],
       [10., 13., 16.],
       [19., 22., 25.]])

In [114]:
data11= np.random.rand(2,3)
data11

array([[0.88796707, 0.99858867, 0.54645468],
       [0.25820168, 0.840505  , 0.49914649]])

In [120]:
data11.sum()

4.0308635928187435

In [124]:
data11.mean()

0.6718105988031239

In [130]:
data11.sum(axis = 0) #열단위 합

array([1.14616875, 1.83909367, 1.04560117])

In [132]:
data11.sum(axis = 1) #행단위 합

array([2.43301042, 1.59785318])

In [134]:
data11.mean(axis = 0) #열단위 평균

array([0.57308438, 0.91954684, 0.52280058])

In [136]:
data11.mean(axis = 1) #행단위 평균

array([0.81100347, 0.53261773])

In [138]:
data11.max()

0.9985886702147649

In [140]:
data11.max(axis = 0) #열단위 평균

array([0.88796707, 0.99858867, 0.54645468])

In [146]:
data11.max(axis = 1) #행단위 평균

array([0.99858867, 0.840505  ])